apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dpl
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: {{ .Values.pod.restartPolicy }}
      containers:
      - name: drawio-app
        image: {{ .Values.containers.app.image }}
        resources:
          limits:
            memory: {{ .Values.containers.app.resources.limits.memory }}
            cpu: {{ .Values.containers.app.resources.limits.cpu }}
        ports:
        - containerPort: 8080
        livenessProbe:
          exec:
            command: ["/bin/bash", "-c", "curl -f http://localhost:8080 || exit 1"]
          initialDelaySeconds: 10
          periodSeconds: 90
          timeoutSeconds: 10
          failureThreshold: 5
