repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.2
    set:
      - name: crds.enabled
        value: true

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    set:
      - name: controller.service.externalTrafficPolicy
        value: Local

  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard

  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/kube-prometheus-stack
    set:
      - name: grafana.defaultDashboardsTimezone
        value: Europe/Moscow
      - name: grafana.adminUser
        value: admin
      - name: grafana.adminPassword
        value: prom-operator

  - name: marzban
    namespace: marzban-ns
    chart: apps/marzban
    values:
      - config:
          vpn:
            vless:
              dest: google.com:443
              serverNames: ["google.com"]
              privateKey: AJPbj4ftkYhB_KG1amEVLG4NK51pdmsCGH6ScU6w62Q
              SpiderX: /example
              shortIds: ea1058117be12087
              port: 30443
            shadowsocks:
              port: 30444
    needs:
      - cert-manager/cert-manager

  - name: drawio
    namespace: drawio-ns
    chart: apps/drawio

  - name: pasta
    namespace: pasta-ns
    chart: apps/pasta

  - name: plantuml
    namespace: plantuml-ns
    chart: apps/plantuml

  - name: tools
    namespace: tools-ns
    chart: apps/tools

  - name: vcenter
    namespace: vcenter-ns
    chart: apps/vcenter
