apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dpl
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: {{ .Values.pod.restartPolicy }}
      containers:
      - name: pasta-app
        image: {{ .Values.containers.app.image }}
        resources:
          limits:
            memory: {{ .Values.containers.app.resources.limits.memory }}
            cpu: {{ .Values.containers.app.resources.limits.cpu }}
        env:
        - name: STORAGE_TYPE
          value: "memcached"
        - name: STORAGE_HOST
          value: "127.0.0.1"
        - name: STORAGE_PORT
          value: "11211"
        ports:
        - containerPort: 7777
      - name: pasta-db
        image: {{ .Values.containers.db.image }}
        resources:
          limits:
            memory: {{ .Values.containers.db.resources.limits.memory }}
            cpu: {{ .Values.containers.db.resources.limits.cpu }}
        ports:
        - containerPort: 11211
