network:
  tls:
    issuerName: nginx-issuer
    secretName: nginx-tls
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

  sites:
    - host: k3s.example.com
      ingress:
        name: k3s-proxy
      svc:
        namespace: kubernetes-dashboard
        name: kubernetes-dashboard-kong-proxy
        port: 443
        protocol: HTTPS
      acl:
        - 10.42.0.0/16

    - host: grafana.example.com
      ingress:
        name: grafana-proxy
      svc:
        namespace: prometheus
        name: prometheus-grafana
        port: 80
        protocol: HTTP
      acl:
        - 10.42.0.0/16

    - host: vpn.example.com
      ingress:
        name: marzban-proxy
      svc:
        namespace: marzban-ns
        name: marzban-svc
        port: 8000
        protocol: HTTPS
      acl:
        - 10.42.0.0/16

    - host: vcenter.example.com
      ingress:
        name: vcenter-proxy
      svc:
        namespace: vcenter-ns
        name: vcenter-svc
        port: 8989
        protocol: HTTPS
      acl:
        - 10.42.0.0/16

    - host: pasta.example.com
      ingress:
        name: pasta-proxy
      svc:
        namespace: pasta-ns
        name: pasta-svc
        port: 7777
        protocol: HTTP

    - host: drawio.example.com
      ingress:
        name: drawio-proxy
      svc:
        namespace: drawio-ns
        name: drawio-svc
        port: 8080
        protocol: HTTP

    - host: pluml.example.com
      ingress:
        name: plantuml-proxy
      svc:
        namespace: plantuml-ns
        name: plantuml-svc
        port: 8080
        protocol: HTTP

    - host: tools.example.com
      ingress:
        name: tools-proxy
      svc:
        namespace: tools-ns
        name: tools-svc
        port: 80
        protocol: HTTP
