apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  secretName: {{ .Release.Name }}-tls
  commonName: marzban-dpl.marzban-ns.svc.cluster.local
  dnsNames:
  - marzban-dpl.marzban-ns.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-issuer
    group: cert-manager.io
