apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeName: {{ .Release.Name }}-pv
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
