apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: web
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ports
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: vless
    port: {{ .Values.config.vpn.vless.port }}
    targetPort: {{ .Values.config.vpn.vless.port }}
    nodePort: {{ .Values.config.vpn.vless.port }}
    protocol: TCP
